use madangdb;
-- BOOK 10
-- ORDERS 10
-- CUSTOMER 5
-- SELECT *
-- FROM BOOK, CUSTOMER, ORDERS => 500개 나옴

-- 예제 문제
SELECT *
FROM BOOK, CUSTOMER, ORDERS
WHERE BOOK.BOOKID = ORDERS.BOOKID
	AND ORDERS.CUSTID = CUSTOMER.CUSTID;
  -- AND ORDERID = 1; => 1개나옴 파란색
  
-- 3.21 고객과 고객의 주문에 관한 데이터를 모두 나타내시오.
SELECT *
FROM CUSTOMER, ORDERS
WHERE CUSTOMER.CUSTID = ORDERS.CUSTID;

-- 3.22 고객과 고객의 주문에 관한 데이터를 고객별로 정렬하여 나타내시오.
SELECT *
FROM CUSTOMER, ORDERS
WHERE CUSTOMER.CUSTID = ORDERS.CUSTID
ORDER BY CUSTOMER.NAME;

-- 3.23 고객의 이름과 고객이 주문한 도서의 판매가격을 검색하시오.
SELECT CUSTOMER.NAME, ORDERS.SALEPRICE
FROM CUSTOMER, ORDERS
WHERE CUSTOMER.CUSTID = ORDERS.CUSTID;

-- 3.24 고객별로 주문한 모든 도서의 총판매액을 구하고, 고객별로 정렬하시오.
-- SELECT NAME, SUM(SALEPRICE)
-- FROM CUSTOMER, ORDERS
-- WHERE CUSTOMER.CUSTID = ORDERS.CUSTID
-- GROUP BY CUSTOMER.NAME
-- ORDER BY CUSTOMER.NAME;


-- 3.25 고객의 이름과 고객이 주문한 도서의 이름을 구하시오.
SELECT CUSTOMER.NAME, BOOK.BOOKNAME
FROM CUSTOMER, ORDERS, BOOK
WHERE CUSTOMER.CUSTID = ORDERS.CUSTID AND ORDERS.BOOKID = BOOK.BOOKID;

-- 3.26 가격이 20,000원인 도서를 주문한 고객의 이름과 도서의 이름을 구하시오.
SELECT CUSTOMER.NAME, BOOK.BOOKNAME
FROM CUSTOMER, BOOK, ORDERS
WHERE CUSTOMER.CUSTID=ORDERS.CUSTID AND ORDERS.BOOKID=BOOK.BOOKID
	AND BOOK.PRICE=20000;

-- 3.27 도서를 구매하지 않은 고객을 포함해 고객의 이름과 고객이 주문한 도서의 판매가격을 구하시오.
SELECT CUSTOMER.NAME, SALEPRICE
FROM CUSTOMER LEFT OUTER JOIN ORDERS ON 
	CUSTOMER.CUSTID = ORDERS.CUSTID;