SELECT CUSTID ID
FROM (SELECT * FROM CUSTOMER )A;

-- 3-28. 가장 비싼 도서의 이름을 나타내시오.
SELECT BOOKNAME
FROM BOOK
WHERE PRICE = (SELECT MAX(BOOK.PRICE) FROM BOOK);

-- 3-29. 도서를 구매한 적이 있는 고객의 이름을 검색하시오.
-- SELECT DISTINCT CUSTOMER.NAME
-- FROM CUSTOMER
-- JOIN ORDERS ON CUSTOMER.CUSTID = ORDERS.CUSTID;

SELECT NAME
FROM CUSTOMER
WHERE CUSTID IN (SELECT CUSTID FROM ORDERS);

-- 3-30. 대한미디어에서 출판한 도서를 구매한 고객의 이름을 나타내시오.
SELECT NAME
FROM CUSTOMER
WHERE CUSTID IN(SELECT CUSTID
				FROM ORDERS
				WHERE BOOKID IN(SELECT BOOKID
								FROM BOOK
								WHERE PUBLISHER = '대한미디어'));

-- 3-31. 출판사별로 출판사의 평균 도서 가격보다 비싼 도서를 구하시오.
-- 출판사 별로 
-- 출판사의 평균 도서 가격 보다 비싼 도서 (평균도서가격), (그보다 비싼 도서)

SELECT B1.BOOKNAME
FROM BOOK B1
WHERE B1.PRICE > (SELECT AVG(B2.PRICE)
					FROM BOOK B2
                    WHERE B2.PUBLISHER=B1.PUBLISHER);


-- 3-32. 대한민국에 거주하는 고객의 이름과 도서를 주문한 고객의 이름을 나타내시오.
-- 고객의 이름
-- 대학민국에 거주하는 고객
-- 도서를 주문한 고객
SELECT NAME
FROM  CUSTOMER
WHERE ADDRESS LIKE '대한민국%'
UNION
SELECT NAME FROM CUSTOMER
WHERE CUSTID IN(SELECT CUSTID FROM ORDERS);

-- 3-33. 주문이 있는 고객의 이름과 주소를 나타내시오.
SELECT NAME, 

