-- GROUP BY 실습
-- 3-15. 고객이 주문한 도서의 총판매액을 구하시오
-- 고객이 주문한 => ORDERS
-- 고객ID별인가? 
SELECT CUSTOMER.CUSTID, SUM(SALEPRICE)
FROM CUSTOMER, ORDERS
GROUP BY CUSTOMER.CUSTID;

-- 3-16. 2번 김연아 고객이 주문한 도서의 총판매액을 구하시오.
SELECT NAME,SUM(SALEPRICE)
FROM CUSTOMER, ORDERS
WHERE NAME= '김연아'
 AND ORDERS.CUSTID = CUSTOMER.CUSTID;
 
-- 3-17. 고객이 주문한 도서의 총판매액, 평균값, 최저가, 최고가를 구하시오.
SELECT NAME, BOOKNAME, SUM(SALEPRICE), AVG(SALEPRICE), MIN(SALEPRICE), MAX(SALEPRICE)
FROM CUSTOMER, ORDERS, BOOK
GROUP BY NAME, BOOKNAME;

-- 3-18. 마당서점의 도서 판매 건수를 구하시오.
SELECT COUNT(ORDERID)
FROM ORDERS;

-- 3-19. 고객별로 주문한 도서의 총수량과 총판매액을 구하시오.
SELECT CUSTOMER.NAME, COUNT(*),SUM(SALEPRICE)
FROM ORDERS, CUSTOMER
WHERE ORDERS.CUSTID = CUSTOMER.CUSTID
group by ORDERS.CUSTID;

-- 3-20. 가격이 8000원 이상인 도서를 구매한 고객에 대하여 고객별 주문 도서의 총수량을 구하시오. 
-- 단, 2권 이상 구매한 고객에 대해서만 구하시오.
SELECT CUSTID, COUNT(*)
FROM ORDERS, BOOK
WHERE 8000 <= PRICE
	AND BOOK.BOOKID = ORDERS.BOOKID
GROUP BY CUSTID
HAVING 2 <= COUNT(*);


SELECT CUSTOMER.NAME, SUM(ORDERID) AS TOTAL_QTY
FROM CUSTOMER
JOIN ORDERS ON CUSTOMER.CUSTID = ORDERS.CUSTID
JOIN BOOK ON BOOK.BOOKID = ORDERS.BOOKID
WHERE SALEPRICE >= 8000
GROUP BY CUSTOMER.NAME
HAVING TOTAL_QTY >= 2;
